Template/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Template.Models;

namespace Template.Controllers
{
    public class AdminController : Controller

    {
        frrEntities db = new frrEntities();
        // GET: Admin
        public ActionResult Dashboard()
        {
            return View();
        }
        public ActionResult Messages()
        {
            var query = db.tblContact.ToList();

            return View(query);
        }
        public ActionResult Orders()
        {
            var query = db.tblOrder.ToList();

            return View(query);
        }
       
    }
}

Template/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Template.Models;

namespace Template.Controllers
{

    public class CategoryController : Controller
    {
        frrEntities db = new frrEntities();
        public ActionResult Index()
        {
            var query = db.tblCategory.ToList();
            return View(query);
        }


        // GET: Catagory
        public ActionResult Create()
        {
            return View();
        }
      
        [HttpPost]
        public ActionResult Create(tblCategory c)
        {
            if (ModelState.IsValid)
            {
                tblCategory cat = new tblCategory();
                cat.Name = c.Name;
                db.tblCategory.Add(cat);
                db.SaveChanges();
                return RedirectToAction("Create", "Product");



            }
            else
            {
                TempData["msg"] = "not inserted Category";
            }


            return View();
        }
    }
}

Template/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>FOODHUT</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="lib/lightbox/css/lightbox.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/Content/css/style.css" rel="stylesheet" />

    <script src="~/Content/js/main.js"></script>

</head>
<body>
    <!-- Topbar Start -->
    <div class="container-fluid bg-primary py-3 d-none d-md-block">
        <div class="container">
            <div class="row">
                <div class="col-md-6 text-center text-lg-left mb-2 mb-lg-0">
                    <div class="d-inline-flex align-items-center">
                        <a class="text-white pr-3" href="">FAQs</a>
                        <span class="text-white">|</span>
                        <a class="text-white px-3" href="">Help</a>
                        <span class="text-white">|</span>
                        <a class="text-white pl-3" href="">Support</a>
                    </div>
                </div>
                <div class="col-md-6 text-center text-lg-right">
                    <div class="d-inline-flex align-items-center">
                        <a class="text-white px-3" href="">
                            <i class="fab fa-facebook-f"></i>
                        </a>
                        <a class="text-white px-3" href="">
                            <i class="fab fa-twitter"></i>
                        </a>
                        <a class="text-white px-3" href="">
                            <i class="fab fa-linkedin-in"></i>
                        </a>
                        <a class="text-white px-3" href="">
                            <i class="fab fa-instagram"></i>
                        </a>
                        <a class="text-white pl-3" href="">
                            <i class="fab fa-youtube"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Topbar End -->
    <!-- Navbar Start -->
    <div class="container-fluid position-relative nav-bar p-0">
        <div class="container-lg position-relative p-0 px-lg-3" style="z-index: 9;">
            <nav class="navbar navbar-expand-lg bg-white navbar-light shadow p-lg-0">
                <a href="index.html" class="navbar-brand d-block d-lg-none">
                    <h1 class="m-0 display-4 text-primary"><span class="text-secondary">i</span>CREAM</h1>
                </a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <ul>
                    <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                        <div class="navbar-nav ml-auto py-0">
                            <li class="nav-item">@Html.ActionLink("Home", "Index", "Home", new { @class = "nav-link" })</li>
                            <li class="nav-item">@Html.ActionLink("About", "About", "Home", new { @class = "nav-link" })</li>


                            <li class="nav-item">@Html.ActionLink("Services", "Services", "Home", new { @class = "nav-link" })</li>
                            <li class="nav-item">@Html.ActionLink("Menu", "Menu", "Home", new { @class = "nav-link" })</li>
                        </div>
                        <a href="index.html" class="navbar-brand mx-5 d-none d-lg-block">
                            <h1 class="m-0 display-4 text-primary"><span class="text-secondary">FOOD</span>HUT</h1>
                        </a>
                        <div class="navbar-nav mr-auto py-0">

                            
                            <li class="nav-item">@Html.ActionLink("Contact", "Contact", "Home", new { @class = "nav-link" })</li>
                            
                          
                            
                      
                    @if (Session["User"] != null)
                    {


                        <li class="nav-item">@Html.ActionLink("SignOut", "SignOut", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    }
                    @if (Session["User"] == null)
                    {
                        <li>@Html.ActionLink("Sign In", "Login", "Account", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Sign  Up", "Register", "Account", new { area = "" }, new { @class = "nav-link" })</li>
                    }

                        <li class="nav-item">

                            <a href="@Url.Action("Checkout","Home")" class="nav-link">
                                <div>
                                    <img src="~/Content/img/cart.png" style="width: 40px;
                            height:40px" />
                                </div>
                                <div style="position:absolute">         </div>@Session["item_count"]
                            </a>
                        </li>


                </div>
                </div>
                    </ul>
            </nav>
        </div>
    </div>
    <!-- Navbar End -->
    <!-- Navbar End -->
    <div class="container body-content">
        @RenderBody()
        <!-- Footer Start -->
        <div class="container-fluid footer bg-light py-5" style="margin-top: 90px;">
            <div class="container text-center py-5">
                <div class="row">
                    <div class="col-12 mb-4">
                        <a href="index.html" class="navbar-brand m-0">
                            <h1 class="m-0 mt-n2 display-4 text-primary"><span class="text-secondary">FOOD</span>HUT</h1>
                        </a>
                    </div>
                    <div class="col-12 mb-4">
                        <a class="btn btn-outline-secondary btn-social mr-2" href="#"><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-outline-secondary btn-social mr-2" href="#"><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-outline-secondary btn-social mr-2" href="#"><i class="fab fa-linkedin-in"></i></a>
                        <a class="btn btn-outline-secondary btn-social" href="#"><i class="fab fa-instagram"></i></a>
                    </div>
                    <div class="col-12 mt-2 mb-4">
                        <div class="row">
                            <div class="col-sm-6 text-center text-sm-right border-right mb-3 mb-sm-0">
                                <h5 class="font-weight-bold mb-2">Get In Touch</h5>
                                <p class="mb-2">123 Street, Gulshan-1, Dhaka</p>
                                <p class="mb-0">+012 345 67890</p>
                            </div>
                            <div class="col-sm-6 text-center text-sm-left">
                                <h5 class="font-weight-bold mb-2">Opening Hours</h5>
                                <p class="mb-2">Mon – Sat, 8AM – 5PM</p>
                                <p class="mb-0">Sunday: Closed</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-12">
                      
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->
        <!-- Back to Top -->
        <a href="#" class="btn btn-secondary px-2 back-to-top"><i class="fa fa-angle-double-up"></i></a>


        <!-- JavaScript Libraries -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
        <script src="lib/easing/easing.min.js"></script>
        <script src="lib/waypoints/waypoints.min.js"></script>
        <script src="lib/owlcarousel/owl.carousel.min.js"></script>
        <script src="lib/isotope/isotope.pkgd.min.js"></script>
        <script src="lib/lightbox/js/lightbox.min.js"></script>

        <!-- Contact Javascript File -->
        <script src="mail/jqBootstrapValidation.min.js"></script>
        <script src="mail/contact.js"></script>

        <!-- Template Javascript -->
        <script src="js/main.js"></script>


    </div>


</body>
</html>

Template/Views/Shared/admin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>FOODHUT</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="lib/lightbox/css/lightbox.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/Content/css/style.css" rel="stylesheet" />

    <script src="~/Content/js/main.js"></script>

</head>
<body>
    <!-- Topbar Start -->
    <div class="container-fluid bg-primary py-3 d-none d-md-block">
        <div class="container">
            <div class="row">
                <div class="col-md-6 text-center text-lg-left mb-2 mb-lg-0">
                    <div class="d-inline-flex align-items-center">
                        <a class="text-white pr-3" href="">FAQs</a>
                        <span class="text-white">|</span>
                        <a class="text-white px-3" href="">Help</a>
                        <span class="text-white">|</span>
                        <a class="text-white pl-3" href="">Support</a>
                    </div>
                </div>
                <div class="col-md-6 text-center text-lg-right">
                    <div class="d-inline-flex align-items-center">
                        <a class="text-white px-3" href="">
                            <i class="fab fa-facebook-f"></i>
                        </a>
                        <a class="text-white px-3" href="">
                            <i class="fab fa-twitter"></i>
                        </a>
                        <a class="text-white px-3" href="">
                            <i class="fab fa-linkedin-in"></i>
                        </a>
                        <a class="text-white px-3" href="">
                            <i class="fab fa-instagram"></i>
                        </a>
                        <a class="text-white pl-3" href="">
                            <i class="fab fa-youtube"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Topbar End -->
    <!-- Navbar Start -->
    <div class="container-fluid position-relative nav-bar p-0">
        <div class="container-lg position-relative p-0 px-lg-3" style="z-index: 9;">
            <nav class="navbar navbar-expand-lg bg-white navbar-light shadow p-lg-0">
                <a href="index.html" class="navbar-brand d-block d-lg-none">
                    <h1 class="m-0 display-4 text-primary"><span class="text-secondary">i</span>CREAM</h1>
                </a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <ul>
                    <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                        <div class="navbar-nav ml-auto py-0">
                            <li class="nav-item">@Html.ActionLink("AddCategory", "Create", "Category", new { area = "" }, new { @class = "nav-link" })</li>
                         
                            <li class="nav-item">@Html.ActionLink("Product", "Index", "Product", new { area = "" }, new { @class = "nav-link" })</li>

                           <li class="nav-item">@Html.ActionLink("AddProduct", "Create", "Pruduct", new { @class = "nav-link" })</li>



                        </div>
                        <a href="index.html" class="navbar-brand mx-5 d-none d-lg-block">
                            <h1 class="m-0 display-4 text-primary"><span class="text-secondary">FOOD</span>HUT</h1>
                        </a>
                        <div class="navbar-nav mr-auto py-0">
                          

                            <li class="nav-item">@Html.ActionLink("Messages", "Messages", "Admin", new { area = "" }, new { @class = "nav-link" })</li>
                            <li class="nav-item">@Html.ActionLink("Orders", "Orders", "Admin", new { area = "" }, new { @class = "nav-link" })</li>
                            <li class="nav-item">@Html.ActionLink("SignOut", "SignOut", "Home", new { area = "" }, new { @class = "nav-link" })</li>




</ul>
                

                
                        </div>
                    </div>
        
   
  
    <!-- Navbar End -->
    <!-- Navbar End -->
    <div class="container body-content">
        @RenderBody()
        <!-- Footer Start -->
        <div class="container-fluid footer bg-light py-5" style="margin-top: 90px;">
            <div class="container text-center py-5">
                <div class="row">
                    <div class="col-12 mb-4">
                        <a href="index.html" class="navbar-brand m-0">
                            <h1 class="m-0 mt-n2 display-4 text-primary"><span class="text-secondary">FOOD</span>HUT</h1>
                        </a>
                    </div>
                    <div class="col-12 mb-4">
                        <a class="btn btn-outline-secondary btn-social mr-2" href="#"><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-outline-secondary btn-social mr-2" href="#"><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-outline-secondary btn-social mr-2" href="#"><i class="fab fa-linkedin-in"></i></a>
                        <a class="btn btn-outline-secondary btn-social" href="#"><i class="fab fa-instagram"></i></a>
                    </div>
                    <div class="col-12 mt-2 mb-4">
                        <div class="row">
                            <div class="col-sm-6 text-center text-sm-right border-right mb-3 mb-sm-0">
                                <h5 class="font-weight-bold mb-2">Get In Touch</h5>
                                <p class="mb-2">123 Street,Gulshan-1, Dhaka</p>
                                <p class="mb-0">+012 345 67890</p>
                            </div>
                            <div class="col-sm-6 text-center text-sm-left">
                                <h5 class="font-weight-bold mb-2">Opening Hours</h5>
                                <p class="mb-2">Mon – Sat, 8AM – 5PM</p>
                                <p class="mb-0">Sunday: Closed</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-12">

                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->
        <!-- Back to Top -->
        <a href="#" class="btn btn-secondary px-2 back-to-top"><i class="fa fa-angle-double-up"></i></a>


        <!-- JavaScript Libraries -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
        <script src="lib/easing/easing.min.js"></script>
        <script src="lib/waypoints/waypoints.min.js"></script>
        <script src="lib/owlcarousel/owl.carousel.min.js"></script>
        <script src="lib/isotope/isotope.pkgd.min.js"></script>
        <script src="lib/lightbox/js/lightbox.min.js"></script>

        <!-- Contact Javascript File -->
        <script src="mail/jqBootstrapValidation.min.js"></script>
        <script src="mail/contact.js"></script>

        <!-- Template Javascript -->
        <script src="js/main.js"></script>


    </div>


</body>
</html>